spring.application.name=consumer
rabbitmq.queuename=MY_TEST_QUEUE
server.port=8081

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=xxxxx@gmail.com
spring.mail.password=prnf onrw isso sjff

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true